baseURL = ""
languageCode = "en-us"
title = "Explore"
theme = "hugo-theme-relearn"
[params]
  author = "Paul Matthews"
  showVisitedLinks = false
  disableSearch = true
  ordersectionsby = "weight"
  themeVariant = ["dark-beach", "light-forest", "dark-forest", "relearn-dark", "relearn-light"]
  disableInlineCopyToClipBoard = true
